when:
  - event: [push, manual]
    branch: [main,master]

steps:
  - name: build-app
    image: node:20
    commands:
      - echo "[INFO] starting build process"
      - npm ci
      - npm run build
    
  - name: build-image
    image: woodpeckerci/plugin-docker-buildx
    pull: false
    settings:
      repo: daniool/dms-portfolio
      registry: docker.io
      username: 
        from_secret: docker_usr
      password:
        from_secret: docker_pswd
      tags:
        - "1.3"
      platforms:
        - linux/amd64
      dockerfile: dockerfile
    depends_on: 
      - build-app


  - name: redeploy
    image: curlimages/curl
    environment:
      API_KEY:
        from_secret: portainer_API_key
      CTR_ID:
        from_secret: ctr_id  
    commands :
      - echo "[INFO] starting redeploy process"
      - "curl -k -X POST \"https://danielmichel-lab.mywire.org/api/endpoints/3/docker/containers/$CTR_ID/recreate\" -H \"X-API-Key: $API_KEY\""
    depends_on: 
      - build-image


  