name: build and deploy

on: [workflow_dispatch,push]

jobs:
  
  build-app:
      runs-on: ubuntu-latest
      name: "Build node app"
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Install dependencies
          run: npm install
        - name: Build app

          run: npm run build-prod
  build-image:
      runs-on: ubuntu-latest
      name: "Build and push docker image"
      needs: build-app
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: daniool/dms-portfolio:1.3
  deploy-to-portianer:
      runs-on: ubuntu-latest
      name: "Push Built Image to prod in portainer"
      timeout-minutes: 10
      needs: build-image
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Deploy stack to portainer
          uses: carlrygart/portainer-stack-deploy@v1
          with:
            portainer-host: https://danielmichel-lab.mywire.org
            username: ${{ secrets.PTR_USR}}
            password: ${{ secrets.PTR_API_TOKEN }}
            stack-name: 'dms-portfolio-stack'
            endpoint-id: '3'
            stack-definition: 'docker-compose.yaml'
            image: docker.io/daniool/dms-portfolio:1.3
